apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-envoy-sidecar-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8443
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              upgrade_configs:
                - upgrade_type: websocket
              use_remote_address: true
              skip_xff_append: false
              route_config:
                name: local_route
                virtual_hosts:
                  - name: zipkin
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          timeout: 0s
                          cluster: zipkin
              http_filters:
                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    http_service:
                      server_uri:
                        uri: https://auth:443
                        cluster: auth
                        timeout: 0.25s
{% if deploy %}
                      path_prefix: /api/v1alpha/verify_dev_or_sa_credentials?url=
{% else %}
                      path_prefix: /{{ default_ns.name }}/auth/api/v1alpha/verify_dev_or_sa_credentials?url=
{% endif %}
                      authorization_request:
                        allowed_headers:
                          patterns:
                            exact: "Cookie"
                            ignore_case: true
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain:
                    filename: /ssl-config/prometheus-cert.pem
                  private_key:
                    filename: /ssl-config/prometheus-key.pem
      clusters:
      - name: auth
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: auth
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: auth
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: /ssl-config/prometheus-cert.pem
                private_key:
                  filename: /ssl-config/prometheus-key.pem
              validation_context:
                trusted_ca:
                  filename: /ssl-config/prometheus-outgoing.pem
      - name: zipkin
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: zipkin
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9411
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: zipkin
  name: zipkin
  namespace: {{ default_ns.name }}
spec:
  serviceName: zipkin
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
{% if deploy %}
      priorityClassName: infrastructure
      nodeSelector:
        preemptible: "false"
{% else %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
       - key: "kubernetes.azure.com/scalesetpriority"
         value: "spot"
{% endif %}
      containers:
       - name: zipkin
         image: openzipkin/zipkin
         imagePullPolicy: Always
         ports:
          - containerPort: 9411
            protocol: TCP
         resources:
           requests:
{% if deploy %}
             cpu: "50m"
             memory: 4G
{% else %}
             cpu: "20m"
             memory: "0.75G"
{% endif %}
           limits:
             cpu: "1"
             memory: 10G
       - name: envoy
         image: "{{ global.docker_prefix }}/envoyproxy/envoy:v1.22.3"
         command:
           - /usr/local/bin/envoy
           - --config-path
           - /etc/envoy/envoy.yaml
           - --concurrency
           - "2"
         resources:
           requests:
             cpu: "5m"
             memory: "20M"
           limits:
             cpu: "1"
             memory: "1G"
         ports:
          - containerPort: 443
         volumeMounts:
          - name: ssl-config-prometheus
            mountPath: /ssl-config
            readOnly: true
          - name: zipkin-envoy-sidecar-config
            mountPath: /etc/envoy
            readOnly: true
         readinessProbe:
           tcpSocket:
             port: 8443
           initialDelaySeconds: 5
           periodSeconds: 5
      volumes:
       - name: ssl-config-prometheus
         secret:
           optional: false
           secretName: ssl-config-prometheus
       - name: zipkin-envoy-sidecar-config
         configMap:
           name: zipkin-envoy-sidecar-config
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  ports:
   - port: 443
     protocol: TCP
     targetPort: 8443
  selector:
    app: zipkin
