version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
  - package-ecosystem: "gradle"
    directory: "/hail"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
