apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch
  namespace: {{ default_ns.name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch-cluster-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch
  namespace: {{ default_ns.name }}
subjects:
- kind: ServiceAccount
  name: batch
roleRef:
  kind: Role
  name: batch
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch-{{ default_ns.name }}-default
  namespace: default
subjects:
- kind: ServiceAccount
  name: batch
  namespace: {{ default_ns.name }}
roleRef:
  kind: ClusterRole
  name: batch-cluster-role
  apiGroup: rbac.authorization.k8s.io
