apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-gateway-envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
            # TODO Can I put additional_addresses here to not duplicate for 443?
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
{% for service in subdomains %}
                  - name: {{ service }}
                    domains:
                      - {{ service }}.hail
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          timeout: 0s
                          cluster: {{ service }}
{% endfor %}
{% for namespace in internal_namespaces %}
{% for service in subdomains %}
                      - match:
                          prefix: "/{{ namespace }}/{{ service }}"
                        route:
                          timeout: 0s
                          cluster: {{ namespace }}-{{ service }}
{% endfor %}
{% endfor %}
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
{% for service in subdomains %}
      - name: {{ service }}
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{ service }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ service }}.default.svc.cluster.local
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: /ssl-config/internal-gateway-cert.pem
                private_key:
                  filename: /ssl-config/internal-gateway-key.pem
              validation_context:
                trusted_ca:
                  filename: /ssl-config/internal-gateway-outgoing.pem
{% endfor %}
{% for namespace in internal_namespaces %}
{% for service in subdomains %}
      - name: {{ namespace }}-{{ service }}
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{ namespace }}-{{ service }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ service }}.{{ namespace }}.svc.cluster.local
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: /ssl-config/internal-gateway-cert.pem
                private_key:
                  filename: /ssl-config/internal-gateway-key.pem
              validation_context:
                trusted_ca:
                  filename: /ssl-config/internal-gateway-outgoing.pem
{% endfor %}
{% endfor %}
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-gateway
  labels:
    app: internal-gateway
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: internal-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: internal-gateway
        hail.is/sha: "{{ code.sha }}"
    spec:
      priorityClassName: infrastructure
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
       - key: "kubernetes.azure.com/scalesetpriority"
         value: "spot"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - internal-gateway
              topologyKey: "kubernetes.io/hostname"
      containers:
       - name: internal-gateway
         image: "{{ global.docker_prefix }}/envoy:v1.22.3"
         resources:
           requests:
             cpu: "20m"
             memory: "200M"
           limits:
             cpu: "1"
             memory: "1G"
         env:
         - name: ENVOY_UID
           value: "0"
         ports:
          - containerPort: 80
         volumeMounts:
          - name: ssl-config-internal-gateway
            mountPath: /ssl-config
            readOnly: true
          - name: internal-gateway-envoy-config
            mountPath: /etc/envoy
            readOnly: true
      volumes:
        - name: ssl-config-internal-gateway
          secret:
            optional: false
            secretName: ssl-config-internal-gateway
        - name: internal-gateway-envoy-config
          configMap:
            name: internal-gateway-envoy-config
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: internal-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: internal-gateway
