{% macro cluster(name, dns_name, dns_refresh_rate)  %}
        - name: {{ name }}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          dns_refresh_rate: {{ dns_refresh_rate }}
          load_assignment:
            cluster_name: {{ name }}
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ dns_name }}
                      port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain:
                    filename: /ssl-config/internal-gateway-cert.pem
                  private_key:
                    filename: /ssl-config/internal-gateway-key.pem
                validation_context:
                  trusted_ca:
                    filename: /ssl-config/internal-gateway-outgoing.pem
{% endmacro %}
{% macro ratelimit() %}
                        typed_per_filter_config:
                          envoy.filters.http.local_ratelimit:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                            stat_prefix: http_local_rate_limiter
                            token_bucket:
                              max_tokens: 150
                              tokens_per_fill: 150
                              fill_interval: 1s
                            filter_enabled:
                              runtime_key: local_rate_limit_enabled
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
                            filter_enforced:
                              runtime_key: local_rate_limit_enforced
                              default_value:
                                numerator: 100
                                denominator: HUNDRED
{% endmacro %}

apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-gateway-envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
            # TODO Can I put additional_addresses here to not duplicate for 443?
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
{% for service in subdomains %}
                  - name: {{ service }}
                    domains:
                      - {{ service }}.hail
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          timeout: 0s
                          cluster: {{ service }}
{{ ratelimit() }}
{% endfor %}
                  - name: internal
                    domains:
                      - "internal.hail"
                    routes:
{% for namespace in internal_namespaces %}
{% for service in subdomains %}
                      - match:
                          prefix: "/{{ namespace }}/{{ service }}"
                        route:
                          timeout: 0s
                          cluster: {{ namespace }}-{{ service }}
{{ ratelimit() }}
{% endfor %}
{% endfor %}
              http_filters:
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
{% for service in subdomains %}
{{ cluster(service, service + '.default.svc.cluster.local', '5s') }}
{% endfor %}
{% for namespace in internal_namespaces %}
{% for service in subdomains %}
{{ cluster(namespace + '-' + service, service + '.' + namespace + '.svc.cluster.local', '60s') }}
{% endfor %}
{% endfor %}
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
