apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-gateway-envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
            # TODO Can I put additional_addresses here to not duplicate for 443?
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              upgrade_configs:
                - upgrade_type: websocket
              rds:
                route_config_name: https_routes
                config_source:
                  resource_api_version: V3
                  path_config_source:
                    path: /config_map/xds/rds.yaml
                    watched_directory:
                      path: /config_map/xds
              http_filters:
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
    dynamic_resources:
      cds_config:
        resource_api_version: V3
        path_config_source:
          path: /config_map/xds/cds.yaml
          watched_directory:
            path: /config_map/xds
